stages:
  - build
  - deploy

docker-build-prod:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f Dockerfile.prod --pull -t "$CI_REGISTRY_IMAGE:prod" .
    - docker push "$CI_REGISTRY_IMAGE:prod"
  only:
      - main

deploy-prod:
  image: alpine:3
  stage: deploy
  script:
    - wget --post-data '' "$DEPLOY_TRIGGER_URL_STAGE"
  when: manual
  only:
    - main

docker-build-stage:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f Dockerfile.stage --pull -t "$CI_REGISTRY_IMAGE:stage" .
    - docker push "$CI_REGISTRY_IMAGE:stage"
    - curl -X POST "$DEPLOY_TRIGGER_URL_STAGE"
  only:
      - stage

deploy-stage:
  image: alpine:3
  stage: deploy
  script:
    - wget --post-data '' "$DEPLOY_TRIGGER_URL_STAGE"
  only:
    - stage
