FROM node:14 AS builder

ADD . /build

WORKDIR /build

ENV NODE_OPTIONS --max_old_space_size=8192

RUN npm install

RUN npm run build

RUN npm prune --production

FROM nginx:1 AS deploy

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /build/node_modules ./node_modules
COPY --from=builder /build/build ./dist
COPY --from=builder /build/package.json ./
COPY --from=builder /build/package-lock.json ./

CMD ["nginx"]
